import React from "react";
import { Target, Users, ShieldCheck, LineChart } from "lucide-react";

const About = () => {
  const pillars = [
    {
      icon: Target,
      title: "Practice that mirrors the real thing",
      description:
        "Interviews are generated for your stack and experience level, then scored answer by answer.",
    },
    {
      icon: ShieldCheck,
      title: "Assessments you can trust",
      description:
        "Face detection and tab-switch monitoring keep every session fair for candidates and companies alike.",
    },
    {
      icon: LineChart,
      title: "Progress you can measure",
      description:
        "Every attempt feeds a report, so you can see which topics are improving and which need work.",
    },
    {
      icon: Users,
      title: "One place for both sides",
      description:
        "Students practise and apply; companies post roles, review applications and schedule interviews.",
    },
  ];

  return (
    <div id="about" className="relative bg-black py-20 scroll-mt-24">
      <div className="absolute inset-0 bg-gradient-to-b from-purple-500/5 via-transparent to-pink-500/5"></div>
      <div className="container mx-auto px-4 sm:px-6 lg:px-8">
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 lg:gap-16 items-center">
          <div>
            <h2 className="text-3xl sm:text-4xl md:text-5xl font-bold font-serif mb-4">
              <span className="bg-gradient-to-r from-pink-500 via-purple-500 to-pink-500 bg-clip-text text-transparent">
                About Hiring Wind
              </span>
            </h2>
            <p className="text-gray-400 text-lg mb-6">
              Hiring Wind is an AI-powered hiring platform built around a
              simple idea: the best way to get ready for an interview is to sit
              through one.
            </p>
            <p className="text-gray-400 mb-6">
              Students run proctored mock interviews generated by AI, get their
              answers scored, and apply to roles from the same dashboard.
              Companies post openings, track applicants through every stage,
              and schedule interviews without leaving the panel.
            </p>
            <p className="text-gray-400">
              No secret tricks, no gatekeeping — just honest practice and a
              clear view of where you stand.
            </p>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            {pillars.map((pillar, index) => (
              <div
                key={index}
                className="group relative p-6 rounded-2xl bg-gradient-to-br from-gray-900 to-black border border-pink-500/20 hover:border-pink-500/40 transition-all duration-500"
              >
                <div className="inline-flex p-3 rounded-xl bg-gradient-to-br from-pink-500 to-purple-500 mb-4">
                  <pillar.icon className="w-5 h-5 text-white" />
                </div>
                <h3 className="text-white font-semibold mb-2">
                  {pillar.title}
                </h3>
                <p className="text-sm text-gray-400">{pillar.description}</p>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
};

export default About;
